# Generated by Django 4.2.1 on 2023-09-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0023_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='block',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='election',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
