# Generated by Django 4.2.1 on 2023-11-02 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evs', '0024_remove_vote_block_remove_vote_candidate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain_code', models.CharField(max_length=64)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evs.candidate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
