# Generated by Django 4.2.1 on 2023-11-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0025_blockchaincode_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party_name',
            field=models.CharField(default='Party Name', max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party_symbol',
            field=models.ImageField(blank=True, null=True, upload_to='party_symbols/'),
        ),
    ]
